version: "3"

# We are goind to set context on the current directory
# Volume maps volume from the project's directory into the docker enviroment
# 0.0.0.0 runs on all available addresses on server (?)
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"