version: "3"

# We are goind to set context on the current directory
# Volume maps volume from the project's directory into the docker enviroment
# 0.0.0.0 runs on all available addresses on server (?)
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate && 
            python manage.py runserver 0.0.0.0:8000"
    environment: 
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    # app should be depend on db. db should first start and app should be able to use it
    depends_on: 
      - db

  db:
    image: postgres:10-alpine
    environment: 
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword #In production server we need to add an encrypted environment variable